# Generated by Django 4.2.6 on 2023-10-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator_user', 'کاربر اپراتور'), ('admin_user', 'کاربر ادمین')], default='admin_user', max_length=20),
        ),
    ]
