# Generated by Django 4.2.6 on 2023-10-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal_user', 'کاربر عادی'), ('operator_user', 'کاربر اپراتور'), ('admin_user', 'کاربر ادمین')], default='normal_user', max_length=20),
        ),
    ]
