# Generated by Django 4.2.6 on 2023-10-26 06:18

import apps.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.CharField(default=apps.core.utils.random_str, max_length=12)),
                ('amount', models.PositiveBigIntegerField()),
                ('amount_refund', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_percentage', models.IntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.wallet')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
