# Generated by Django 4.2.6 on 2023-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='discount_expire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
