# Generated by Django 4.2.6 on 2023-11-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_clubconfig_discount_expire_transaction_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubconfig',
            old_name='discount_expire',
            new_name='discount_has_expire',
        ),
    ]
