# Generated by Django 4.2.6 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_rename_discount_expire_clubconfig_discount_has_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='discount_expire_day',
            field=models.IntegerField(default=30),
        ),
    ]
