# Generated by Django 4.2.6 on 2023-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_clubconfig_discount_expire_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_showing',
            field=models.BooleanField(default=True),
        ),
    ]
